title: big blue letters 
author: not putting my name
email: not-my-email@either.punk
theme: time-machine 
description: > # this means to ignore newlines until "baseurl:"
not even a real place

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
